# Generated by Django 4.1.4 on 2023-01-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='3d_models_images')),
                ('other_image1', models.ImageField(blank=True, null=True, upload_to='3d_models_images')),
                ('other_image2', models.ImageField(blank=True, null=True, upload_to='3d_models_images')),
                ('other_image3', models.ImageField(blank=True, null=True, upload_to='3d_models_images')),
                ('other_image4', models.ImageField(blank=True, null=True, upload_to='3d_models_images')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
